//! Launch-context detection. Distinguishes an AppImage-mounted GUI from
//! a dev build so downstream code (launcher, systemd unit generation)
//! can choose the right ExecStart target.

use std::io;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LaunchContext {
    /// GUI is running from an AppImage. `appimage_path` is the absolute
    /// path the user launched (from the runtime-provided APPIMAGE env var),
    /// which is stable across process lifetimes as long as the file is
    /// not moved or renamed.
    AppImage { appimage_path: PathBuf },
    /// Dev build. `cli_binary` is the sibling `logig560` binary next to
    /// the GUI binary — the same convention as today's setup module.
    DevBuild { cli_binary: PathBuf },
}

pub fn detect_launch_context() -> LaunchContext {
    detect_launch_context_with(
        |name| std::env::var(name).ok(),
        std::env::current_exe,
    )
}

pub fn detect_launch_context_with<E, C>(env: E, current_exe: C) -> LaunchContext
where
    E: Fn(&str) -> Option<String>,
    C: Fn() -> io::Result<PathBuf>,
{
    if let Some(path) = env("APPIMAGE") {
        return LaunchContext::AppImage {
            appimage_path: PathBuf::from(path),
        };
    }
    // Dev-build fallback: derive the sibling CLI path from current exe.
    // If current_exe fails (rare), fall back to a relative "logig560".
    let cli_binary = current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(|p| p.join("logig560")))
        .unwrap_or_else(|| PathBuf::from("logig560"));
    LaunchContext::DevBuild { cli_binary }
}

use std::fs;
use std::io::Write as _;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::Path;

use anyhow::{Context, Result, anyhow};

/// Write `<bin_dir>/logig560` as an executable POSIX-sh script that
/// re-execs `appimage_path` with `--cli`. Creates `bin_dir` if missing.
pub fn ensure_launcher(bin_dir: &Path, appimage_path: &Path) -> Result<PathBuf> {
    fs::create_dir_all(bin_dir)
        .with_context(|| format!("create {}", bin_dir.display()))?;
    let launcher = bin_dir.join("logig560");
    let script = format!(
        "#!/bin/sh\n\
         # Auto-generated by G560 Linux Utility.\n\
         # Regenerate via the Setup & Service page if the AppImage moves.\n\
         exec {quoted} --cli \"$@\"\n",
        quoted = shell_single_quote(
            appimage_path
                .to_str()
                .ok_or_else(|| anyhow!("appimage path is not valid utf-8"))?,
        ),
    );
    // Atomic write: temp file + rename in same dir, then chmod 0755.
    let tmp = bin_dir.join(".logig560.tmp");
    {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o755)
            .open(&tmp)
            .with_context(|| format!("open {}", tmp.display()))?;
        file.write_all(script.as_bytes())
            .with_context(|| format!("write {}", tmp.display()))?;
        file.sync_all().ok();
    }
    fs::rename(&tmp, &launcher)
        .with_context(|| format!("rename {} -> {}", tmp.display(), launcher.display()))?;
    // rename preserves mode on the same filesystem; belt-and-suspenders:
    fs::set_permissions(&launcher, fs::Permissions::from_mode(0o755))
        .with_context(|| format!("chmod {}", launcher.display()))?;
    Ok(launcher)
}

/// POSIX single-quote escape: surround with single quotes and replace any
/// embedded ' with '\''.
fn shell_single_quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('\'');
    for ch in value.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Convenience: resolve the user's `~/.local/bin`. Errors if HOME is
/// unset or points at a non-directory (extremely unlikely in a normal
/// session but worth surfacing rather than panicking).
pub fn home_bin_dir() -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| anyhow!("HOME not set"))?;
    Ok(home.join(".local/bin"))
}

/// Convenience: full path to `~/.local/bin/logig560`.
pub fn launcher_path() -> Result<PathBuf> {
    Ok(home_bin_dir()?.join("logig560"))
}
