//! Launch-context detection. Distinguishes an AppImage-mounted GUI from
//! a dev build so downstream code (launcher, systemd unit generation)
//! can choose the right ExecStart target.

use std::fs;
use std::io;
use std::io::Write as _;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LaunchContext {
    /// GUI is running from an AppImage. `appimage_path` is the absolute
    /// path the user launched (from the runtime-provided APPIMAGE env var),
    /// which is stable across process lifetimes as long as the file is
    /// not moved or renamed.
    AppImage { appimage_path: PathBuf },
    /// Dev build. `cli_binary` is the sibling `logig560` binary next to
    /// the GUI binary — the same convention as today's setup module.
    DevBuild { cli_binary: PathBuf },
}

pub fn detect_launch_context() -> LaunchContext {
    detect_launch_context_with(
        |name| std::env::var(name).ok(),
        std::env::current_exe,
    )
}

pub fn detect_launch_context_with<E, C>(env: E, current_exe: C) -> LaunchContext
where
    E: Fn(&str) -> Option<String>,
    C: Fn() -> io::Result<PathBuf>,
{
    if let Some(path) = env("APPIMAGE") {
        return LaunchContext::AppImage {
            appimage_path: PathBuf::from(path),
        };
    }
    // Dev-build fallback: derive the sibling CLI path from current exe.
    // If current_exe fails (rare), fall back to a relative "logig560".
    let cli_binary = current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(|p| p.join("logig560")))
        .unwrap_or_else(|| PathBuf::from("logig560"));
    LaunchContext::DevBuild { cli_binary }
}

/// Write `<bin_dir>/logig560` as an executable POSIX-sh script that
/// re-execs `appimage_path` with `--cli`. Creates `bin_dir` if missing.
pub fn ensure_launcher(bin_dir: &Path, appimage_path: &Path) -> Result<PathBuf> {
    fs::create_dir_all(bin_dir)
        .with_context(|| format!("create {}", bin_dir.display()))?;
    let launcher = bin_dir.join("logig560");
    let script = format!(
        "#!/bin/sh\n\
         # Auto-generated by G560 Linux Utility.\n\
         # Regenerate via the Setup & Service page if the AppImage moves.\n\
         exec {quoted} --cli \"$@\"\n",
        quoted = shell_single_quote(
            appimage_path
                .to_str()
                .ok_or_else(|| anyhow!("appimage path is not valid utf-8"))?,
        ),
    );
    // Atomic write: temp file + rename in same dir, then chmod 0755.
    let tmp = bin_dir.join(".logig560.tmp");
    let write_tmp = || -> Result<()> {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o755)
            .open(&tmp)
            .with_context(|| format!("open {}", tmp.display()))?;
        file.write_all(script.as_bytes())
            .with_context(|| format!("write {}", tmp.display()))?;
        file.sync_all().ok();
        Ok(())
    };
    if let Err(err) = write_tmp() {
        let _ = fs::remove_file(&tmp);
        return Err(err);
    }
    fs::rename(&tmp, &launcher)
        .with_context(|| format!("rename {} -> {}", tmp.display(), launcher.display()))?;
    // rename preserves mode on the same filesystem; belt-and-suspenders:
    fs::set_permissions(&launcher, fs::Permissions::from_mode(0o755))
        .with_context(|| format!("chmod {}", launcher.display()))?;
    Ok(launcher)
}

/// POSIX single-quote escape: surround with single quotes and replace any
/// embedded ' with '\''.
fn shell_single_quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('\'');
    for ch in value.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Convenience: resolve the user's `~/.local/bin`. Errors if HOME is unset.
pub fn home_bin_dir() -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| anyhow!("HOME not set"))?;
    Ok(home.join(".local/bin"))
}

/// Convenience: full path to `~/.local/bin/logig560`.
pub fn launcher_path() -> Result<PathBuf> {
    Ok(home_bin_dir()?.join("logig560"))
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum LauncherState {
    /// No launcher script found.
    Missing,
    /// Launcher exists and its embedded AppImage path matches the current one.
    Current,
    /// Launcher exists but points at a different AppImage path (moved/renamed).
    Stale { embedded: PathBuf },
    /// Launcher exists but its contents are not a script we recognise
    /// (user hand-edited or a stale foreign file).
    Unknown,
}

pub fn verify_launcher_at(bin_dir: &Path, current_appimage: &Path) -> LauncherState {
    let launcher = bin_dir.join("logig560");
    let contents = match fs::read_to_string(&launcher) {
        Ok(c) => c,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return LauncherState::Missing,
        Err(_) => return LauncherState::Unknown,
    };
    let Some(embedded) = extract_launcher_appimage_path(&contents) else {
        return LauncherState::Unknown;
    };
    if embedded == current_appimage {
        LauncherState::Current
    } else {
        LauncherState::Stale { embedded }
    }
}

pub fn verify_launcher(current_appimage: &Path) -> Result<LauncherState> {
    Ok(verify_launcher_at(&home_bin_dir()?, current_appimage))
}

fn extract_launcher_appimage_path(script: &str) -> Option<PathBuf> {
    // The generated script's exec line is:  exec 'PATH' --cli "$@"
    for line in script.lines() {
        let line = line.trim_start();
        if !line.starts_with("exec ") {
            continue;
        }
        let rest = line.trim_start_matches("exec ").trim_start();
        if !rest.starts_with('\'') {
            return None;
        }
        // Find the closing single quote, accounting for the '\'' escape.
        let mut chars = rest.char_indices();
        chars.next(); // consume opening '
        let mut buf = String::new();
        while let Some((i, ch)) = chars.next() {
            if ch == '\'' {
                // Check for '\'' escape: next three chars should be \\''.
                let tail = &rest[i..];
                if tail.starts_with("'\\''") {
                    buf.push('\'');
                    // Skip \''
                    chars.next();
                    chars.next();
                    chars.next();
                    continue;
                }
                return Some(PathBuf::from(buf));
            }
            buf.push(ch);
        }
        return None;
    }
    None
}

/// Desktop unit template baked into the GUI binary.
const DESKTOP_UNIT_TEMPLATE: &str =
    include_str!("../../../../systemd/logig560-desktop.service.in");

/// Substitute @LAUNCHER@ in the desktop unit template. `exec_target` is
/// the launcher path (AppImage mode) or CLI binary path (dev mode).
pub fn render_desktop_unit(_ctx: &LaunchContext, exec_target: &Path) -> String {
    DESKTOP_UNIT_TEMPLATE.replace("@LAUNCHER@", &exec_target.to_string_lossy())
}

/// Gaming unit template baked into the GUI binary.
const GAMING_UNIT_TEMPLATE: &str =
    include_str!("../../../../systemd/logig560-gaming.service.in");

/// Substitute @LAUNCHER@ in the gaming unit template. `exec_target` is
/// the launcher path (AppImage mode) or CLI binary path (dev mode).
pub fn render_gaming_unit(_ctx: &LaunchContext, exec_target: &Path) -> String {
    GAMING_UNIT_TEMPLATE.replace("@LAUNCHER@", &exec_target.to_string_lossy())
}
