[package]
name = "logilightshow"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[workspace]
members = [".", "crates/logilightshow-api"]
resolver = "3"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
ashpd = { version = "0.13.12", default-features = false, features = ["tokio", "screencast"] }
clap = { version = "4.5", features = ["derive"] }
directories = "6"
futures-util = "0.3"
gstreamer = "0.25"
gstreamer-app = "0.25"
gstreamer-video = { version = "0.25", features = ["v1_24"] }
hdrhistogram = "7.5"
logilightshow-api = { path = "crates/logilightshow-api" }
palette = "0.7"
pipewire = { version = "0.10", features = ["v1_2_0"] }
rusb = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.51", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "test-util", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
proptest = "1.9"
tempfile = "3.27"
